version: "3.8"

services:
  flask:
    build: .
    container_name: flask_chatbot
    environment:
      - N8N_WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    expose:
      - "5000"
    networks:
      adguard_local_macvlan_network:
        ipv4_address: 10.0.0.192

  nginx:
    image: nginx:latest
    container_name: nginx_chatbot
    volumes:
      - /etc/docker-configs/nginx/my-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flask
    networks:
      adguard_local_macvlan_network:
        ipv4_address: 10.0.0.200

networks:
  adguard_local_macvlan_network:
    external: true
